# Generated by Django 4.0.6 on 2022-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='coment_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
