# Generated by Django 4.0.6 on 2022-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0002_alter_coment_coment_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
